services:
  web:
    image: nginx:latest

    ports:
      - '85:80'
    volumes:
      - '/home/aldar/PhpstormProjects/project2/Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - '/home/aldar/PhpstormProjects/project2:/var/www/html'

  php-fpm:
    build: ./Docker/php
    restart: always
    volumes:
      - '.:/var/www/html'

  postgres:
    image: postgres:13
    ports:
      - '5431:5432'
    volumes:
      - './Docker/postgres/data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


